export const ebAggregates: readonly string[] = [
	// energieträgergruppen
	"Gesamtenergiebilanz",
	"Elektrische Energie",
	"ERNEUERBARE",
	"KOHLE",
	"ÖL",
	"GAS",
	"Fernwärme",

	// erneuerbare
	"Wasserkraft",
	"Wind",
	"Photovoltaik",

	// fossil_fest
	"Steinkohle",
	"Braunkohle",
	"Braunkohlen-Briketts",
	"Brenntorf",
	"Koks",
	"Brennbare Abfälle",

	// fossil_flüssig
	"Erdöl",
	"Sonstiger Raffinerieeinsatz",
	"Benzin",
	"Petroleum",
	"Diesel",
	"Gasöl für Heizzwecke",
	"Heizöl",
	"Flüssiggas",
	"Sonstige Prod. d. Erdölverarb.",

	// fossil_gasförmig
	"Gichtgas",
	"Kokereigas",
	"Raffinerie-Restgas",
	"Mischgas",
	"Erdgas",

	// biogen_fest
	"Scheitholz",
	"Pellets+Holzbriketts",
	"Holzabfall",
	"Holzkohle",
	"Ablaugen",
	"Sonst. Biogene fest",
	"Hausmüll Bioanteil",

	// biogen_flüssig
	"Bioethanol",
	"Biodiesel",
	"Sonst. Biogene flüssig",

	// biogen_gasförmig
	"Deponiegas",
	"Klärgas",
	"Biogas",

	// umgebungswärme
	"Geothermie",
	"Umgebungswärme",
	"Solarwärme",
	"Reaktionswärme",

	//  wasserkraft
	"WK<=1MW",
	"WK<=10MW",
	"WK>10MW",

	// abfall
	"Brennbare Abfälle",
	"Industrieabfall",
	"Hausmüll Bioanteil",
	"Hausmüll nicht erneuerbar",

	// erzeugung
	"Inländ. Erzeugung v. Rohenergie",
	"Importe",
	"Lager",
	"Recycling/Prod. Trans.",
	"Exporte",

	// umwandlung
	"Umwandlungseinsatz",
	"Umwandlungsausstoß",

	// verbrauch
	"Bruttoinlandsverbrauch",
	"Verbrauch des Sektors Energie",
	"Transportverluste",
	"Nichtenergetischer Verbrauch",
	"Energetischer Endverbrauch",

	// sektoren
	"Eisen- und Stahlerzeugung",
	"Chemie und  Petrochemie",
	"Nicht Eisen Metalle",
	"Steine und Erden, Glas",
	"Fahrzeugbau",
	"Maschinenbau",
	"Bergbau",
	"Nahrungs- und Genußmittel, Tabak",
	"Papier und Druck",
	"Holzverarbeitung",
	"Bau",
	"Textil und Leder",
	"Sonst. Produzierender Bereich",
	"Eisenbahn",
	"Sonstiger Landverkehr",
	"Transport in Rohrfernleitungen",
	"Binnenschiffahrt",
	"Flugverkehr",

	// sektoren_aggregiert
	"Öffentliche und Private Dienstleistungen",
	"Private Haushalte",
	"Landwirtschaft",
	"Produzierender Bereich",
	"Verkehr",
	"Sonstige",

	// sektoren_energie
	"Gewinnung von Erdöl und Erdgas",
	"Kohlenbergbau",
	"Mineralölverarbeitung",
	"Kokerei",
	"Hochofen",
	"Energieversorgung (Elektrizität, Erdgas, Fernwärme)"
] as const

export const neaAggregates: readonly string[] = [
	"Gesamt (ohne E1 - E7)",
	"Produzierender Bereich Gesamt",
	"Transport Gesamt",
	"Sonstige Wirtschaftsbereiche Gesamt",
	"Eisen- und Stahlerzeugung",
	"Chemie und  Petrochemie",
	"Nicht Eisen Metalle",
	"Steine und Erden, Glas",
	"Fahrzeugbau",
	"Maschinenbau",
	"Bergbau",
	"Nahrungs- und Genußmittel, Tabak",
	"Papier und Druck",
	"Holzverarbeitung",
	"Bau",
	"Textil und Leder",
	"Sonst. Produzierender Bereich",
	"Eisenbahn",
	"Sonstiger Landverkehr",
	"Transport in Rohrfernleitungen",
	"Binnenschiffahrt",
	"Flugverkehr",
	"Offentliche und Private Dienstleistungen",
	"Private Haushalte",
	"Landwirtschaft"
] as const

export const resAggregates: readonly string[] = [
	"Energetischer Endverbrauch Erneuerbare (TJ)",
	"Elektrische Energie Produktion erneuerbar (TJ)",
	"Fernwärme Produktion erneuerbar (TJ)",
	"Anrechenbarer Erneuerbare (TJ)",
	"Energetischer Endverbrauch (TJ)",
	"Verbrauch Sektor Energie (TJ)",
	"Verluste (TJ)",
	"Verbrauch Sektor Energie im Hochofen (TJ)",
	"Denominator (TJ)",
	"Anteil anrechenbare Erneuerbare insgesamt",
	"Anteil anrechenbare Erneuerbare Elektrizitätserzeugung",
	"Anteil anrechenbare Erneuerbare Fernwärmeerzeugung",
	"Anteil anrechenbare Erneuerbare Verkehr",
	"Anteil anrechenbare Erneuerbare Industrie",
	"Anteil anrechenbare Erneuerbare Dienstleistungen",
	"Anteil anrechenbare Erneuerbare Haushalte",
	"Anteil Erneuerbare Landwirtschaft",
	"Biokraftstoffe nachhaltig",
	"Strom erneuerbar",
	"Summe Zähler",
	"fossile Kraftstoffe",
	"Biokraftstoffe Schiene & Straße",
	"Strom Landverkehr",
	"Summe Nenner",
	"E-KFZ",
	// res_bagg_1
	"Scheitholz",
	"Holzbasierte Energieträger",
	"Sonstige Biogene fest",
	"Biogas",
	"Biotreibstoffe nachhaltig pur",
	"Biotreibstoffe nachhaltig beigemengt",
	"Laugen",
	"Müll erneuerbar",
	"Solarwärme",
	"Geothemie",
	"Umgebungswärme",
	"Wasserkraft ohne Pumpe normalisiert (MWh)",
	"Wasserkraft mit Pumpe normalisiert (MWh)",
	"Primärstrom Wind normalisiert (MWh)",
	"Primärstrom Fotovoltaik (MWh)",
	"Primärstrom Geothermie (MWh)",
	"Sekundärstrom erneuerbar (MWh)",
	"Gesamtstrom erneuerbar (MWh)",
	"Müll erneuerbar",
	"Holzbasierte Energieträger",
	"Biogas",
	"Sonstige Biogene flüssig",
	"Laugen",
	"Sonstige Biogene fest",
	"Geothermie",
	// res_bagg_2
	"Installierte Kapazität ohne Pumpe (MW)",
	"Primärstrom Wasser real (MWh)",
	"Installierte Kapazität mit Pumpe (MW)",
	"Erzeugung aus natürlichem Zufluß (MWh)",
	"Ausnutzungsdauer (h)",
	"Primärstrom Wasser real (MWh)",
	"Erzeugung aus gepumptem Zufluß (MWh)",
	"Installierte Kapazität real (kW)",
	"Installierte Kapazität normalisiert (kW)",
	"Primärstrom Wind real (MWh)",
	"Müll erneuerbar",
	"Holz-basiert",
	"Biogas",
	"Biogene flüssig",
	"Laugen",
	"sonst Biogene fest",
] as const
